
mongodb:
    host: localhost
    port: 27017

webs:

  - host: "jenbrister.co.uk"
    root: "/home/benjamin/dev/github/ThinCMS/webs/demo"
    default: 1
    mongodb_name: "testdb"

  - host: "jenbrister.co.uk"
    root: "/home/benjamin/dev/github/ThinCMS/webs/jenbrister"
    mongodb_name: "jenbrister"

  - robertdancer:
    root: "/home/benjamin/dev/github/ThinCMS/webs/robertdancer"
    host: "robertdancer.co.uk"
    mongodb_name: "robertdancer"

