
mongodb:
    host: localhost
    port: 27017

webs:

  - host: localhost"
    root: /home/benjamin/dev/github/ThinCMS/webs/demo
    default: 1
    mongodb_name: testdb
    admin_user: demo
    admin_pass: d3mo
    entrytypes:
      - name: Pages
        elements: 
          - name: title
            type: Text
          - name: content
            type: HTML
      - name: Blog
        elements: 
          - name: title
            type: Text
          - name: date
            type: Date
          - name: content
            type: LargeText

  - host: jenbrister.co.uk
    root: /home/benjamin/dev/projects/jenbrister/tt_site
    mongodb_name: jenbrister
    admin_user: jen
    admin_pass: brister
    entrytypes:
      - name: Pages
        elements: 
          - name: title
            type: Text
          - name: heading
            type: LargeText
          - name: content
            type: HTML
      - name: Gigs
        elements: 
          - name: title
            type: Text
          - name: date
            type: Date
          - name: content
            type: LargeText
      - name: Blog
        elements: 
          - name: title
            type: Text
          - name: content
            type: LargeText

  - robertdancer:
    root: /home/benjamin/dev/github/ThinCMS/webs/robertdancer
    host: robertdancer.co.uk
    mongodb_name: robertdancer
    admin_user: rob
    admin_pass: dancer
    entrytypes:
      - name: Job
        elements: 
          - name: title
            type: Text
          - name: content
            type: LargeText
          - name: pictures
            type: Images
        
