
mongodb:
    host: localhost
    port: 27017

webs:

  - host: localhost"
    root: ./webs/demo
    default: 1
    mongodb_name: demo
    admin_user: demo
    admin_pass: d3mo
    entrytypes:
      - name: Pages
        elements: 
          - name: title
            type: Text
          - name: content
            type: HTML
      - name: Blog
        elements: 
          - name: title
            type: Text
          - name: date
            type: Date
          - name: content
            type: LargeText

  - host: jenbrister.co.uk
    root: /home/benjamin/dev/projects/jenbrister/tt_site
    mongodb_name: jenbrister
    admin_user: jen
    admin_pass: brister
    entrytypes:
      - name: Pages
        elements: 
          - name: title
            type: Text
          - name: heading
            type: LargeText
          - name: content
            type: HTML
      - name: Upcoming
        elements: 
          - name: title
            type: Text
          - name: date
            type: Date
          - name: heading
            type: LargeText
          - name: content
            type: HTML
      - name: Thoughts
        elements: 
          - name: title
            type: Text
          - name: heading
            type: LargeText
          - name: content
            type: HTML
    time2str:
      date: '%d/%m/%y'
      datetime: '%d/%m/%y %H:%M'

